# Default state for all rules
default: true

# MD013/line-length - Line length
MD013:
  line_length: 99999
  code_block_line_length: 99
  tables: false

# MD024/no-duplicate-heading - Multiple headers with same content
MD024:
  siblings_only: true

# MD028/no-blanks-blockquote - Blank line inside blockquote
MD028: false

# MD035/hr-style - Horizontal rule style
MD035:
  style: "---"
