name: test
on: [push, workflow_call]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ windows-latest, ubuntu-latest, macos-latest ]
        python-version: [ "3.9", "3.11", "3.13" ]

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3.0.1
      with:
        poetry-version: 2.0.1

    - name: Setup Poetry
      if: runner.os == 'macOS'
      run: poetry env use ${{ matrix.python-version }}

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: poetry run pytest --mypy --cov-branch --cov-report=xml

    - name: Upload coverage reports to Codecov
      if: ${{ (matrix.os == 'ubuntu-latest') && (matrix.python-version == '3.13') }}
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: abatilo/actions-poetry@v3.0.1
        with:
          poetry-version: 2.0.1
      - name: Install dependencies
        run: poetry install
      - uses: pre-commit/action@v3.0.1

  check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        name: Check links in markdown files
        with:
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'


  benchmark:
    needs: [test, qa]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Install Poetry
      uses: abatilo/actions-poetry@v3.0.1
      with:
        poetry-version: 2.0.1

    - name: Install dependencies
      run: poetry install

    - name: Run tests
      run: poetry run pytest --benchmark-enable --benchmark-only
