on:
  release:
    types: [published]

jobs:
  pypi-publish:
    name: Build and publish Python 🐍 distributions 📦 to PyPI
    runs-on: ubuntu-latest
    environment:
      name: PyPI
      url: https://pypi.org/p/athreading
    permissions:
      id-token: write  # IMPORTANT: this permission is mandatory for trusted publishing
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - name: Install Poetry
      uses: abatilo/actions-poetry@v4.0.0
      with:
        poetry-version: 1.8.5
    - name: Poetry Build
      run: poetry build
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@v1.12.3

  # gitlab-oci-publish:
  #   runs-on: ubuntu-latest
  #   needs: test
  #   # The following steps to build a Docker image and publish to the GitHub container registry on release. Alternatively, can replace with other publising steps (ie. publishing to PyPI, deploying documentation etc.)
  #   steps:
  #     - name: Login to GitHub Container Registry
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Get image metadata
  #       id: meta
  #       uses: docker/metadata-action@v5
  #       with:
  #         images: ghcr.io/${{ github.repository }}
  #     - name: Build and push Docker image
  #       uses: docker/build-push-action@v6
  #       with:
  #         push: true
  #         tags: ${{ steps.meta.outputs.tags }}
